security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\UserEntity
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator

        public:
            pattern: ^/(public)
            security: false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/(auth|api)
            stateless: true
            provider: app_user_provider
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh

        main:
            lazy: true
            provider: app_user_provider
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/public/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/auth/, roles: ROLE_USER }
        
        - { path: ^/api/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
