security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\UserEntity
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
                password_path: password

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/(account|api)
            stateless: true
            provider: app_user_provider
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh

        main:
            lazy: true
            provider: app_user_provider
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/account/(login_check|token/refresh), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/register_new_user, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/verify_account, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/resend_verify_mail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/password_change, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password-reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/account/logout, roles: ROLE_USER }
        - { path: ^/account/mfa, roles: ROLE_USER }
        - { path: ^/api/greetings, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }

        
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
