services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Event Listener für Account Verified
    App\EventListener\AccountVerifiedListener:
        arguments:
            $whitelistedRoutes:
                - 'account_register_new_user'
                - 'login_check'
                - 'verify_account'
                - 'account_resend_verify_mail'
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    # Standardmäßige Service-Registrierung für src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
