services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Event Listener für Account Verified
    App\EventListener\AccountVerifiedListener:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventListener\DeviceCheckListener:
        tags:
            - { name: 'kernel.event_listener', event: 'lexik_jwt_authentication.on_authentication_success', method: 'onAuthenticationSuccess' }


    # Standardmäßige Service-Registrierung für src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
