services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Event Listener für Account Verified
    App\EventListener\AccountVerifiedListener:
        tags:
            - { name: 'kernel.event_subscriber' }
    
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'